import { Chewy } from "next/font/google";

import "./globals.css";

const chewy = Chewy({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Bluey Quiz Game",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en" className={chewy.className}>
      <body>
        <div className="flex items-center justify-center min-h-screen bg-cyan-50">
          <div className="bg-cyan-400 m-3 shadow-2xl rounded-2xl px-60 pb-40 pt-20">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
