import { Chewy } from "next/font/google";

import "./globals.css";

const chewy = Chewy({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Bluey Quiz Game",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en" className={chewy.className}>
      <body>
        {/* global container */}
        <div className="flex items-center justify-center min-h-screen bg-cyan-50">
          {children}
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
