const DUMMY_SCORES = [	
		{
		 id: 1,
		 name: 'Muffin',
		 level: 'Medium',
		 model: 'Gemini',
		 score: 2
		},
		{
			id: 2, 
			name: 'Bandit',
			level: 'Easy',
			model: 'Claude',
			score: 4
		},
		{
			id: 3,
			name: 'Lila',
			level: 'Medium',
			model: 'Deepseek',
			score: 6
		}
]

// retreive top scores
export async function getHighScores(){
	// generated by nextjs docs AI
  await new Promise((resolve) => {
    setTimeout(() => {
      resolve()
    }, 3000) // delay for UI purposes
  })

	// sort scores from highest to lowest
	return (DUMMY_SCORES.sort((a,b) => b.score - a.score))
}

export function getScoreID(id){
	return (DUMMY_SCORES.filter((score) => score.id === id))
}

