const DUMMY_SCORES = [	
		{
		 id: 1,
		 name: 'Muffin',
		 country: 'Australia',
		 score: 2
		},
		{
			id: 2, 
			name: 'Bandit',
			country: 'United States',
			score: 4
		},
		{
			id: 3,
			name: 'Lila',
			country: 'Italy',
			score: 6
		}
]

// retreive top scores
export async function getHighScores(){
	// generated by nextjs docs AI
  await new Promise((resolve) => {
    setTimeout(() => {
      resolve()
    }, 3000) // delay for UI purposes
  })

	// sort scores from highest to lowest
	return (DUMMY_SCORES.sort((a,b) => b.score - a.score))
}

